### ISSUE TITLE
Davit ani pisat nevie!

### ISSUE THREAD

**Issue by Pablo-Diego-Jose-Francisco-De-Papa-II** [analnyroztahovac/Python-S#4]
https://github.com/analnyroztahovac/Python-S/blob/760ee05bfad9e72ff6ba077144ab6ec4c5ba76c5/3.%20Rocnik/Cvicenia/20-12-2022.py#L41

**Comment by davight** [comment]
PRni fix

**Comment by Pablo-Diego-Jose-Francisco-De-Papa-II** [comment]
prdni si
